#!/bin/dash

#systemctl --user import-environment ANDROID_HOME PATH XDG_SEAT XDG_SEAT_PATH XDG_SESSION_CLASS XDG_SESSION_ID XDG_SESSION_PATH XDG_SESSION_TYPE XDG_VTNR DESKTOP_SESSION XDG_SESSION_DESKTOP XDG_CURRENT_DESKTOP GTK_MODULES MOTD_SHOWN XAUTHORITY SHLVL GTK3_MODULES QT_QPA_PLATFORMTHEME HG DEBUGINFOD_URLS _JAVA_AWT_WM_NONREPARENTING SSH_ASKPASS SSH_ASKPASS_REQUIRE NVM_BIN NVM_DIR NVM_CD NVM_INC PAM_KWALLET5_LOGIN

# set the alignment of monitors
#xrandr --output DP-1 --primary --mode 1920x1080 --rate 144 --right-of HDMI-1 --output HDMI-1 --mode 1920x1080 --rate 144
#xrandr --output HDMI-1 --mode 1920x1080 --rate 60 --rotate left --pos 0x0 --output DP-1 --primary --mode 1920x1080 --rate 120 --pos 1080x295 --rotate normal

#if xrandr | grep "HDMI-1 disconnected"; then
bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
#else
#    bspc wm -O DP-1 HDMI-1
#    bspc monitor DP-1 -d I II III IV V
#    bspc monitor HDMI-1 -d VI VII VIII IX X
#fi

# focus monitor on start up
#bspc monitor DP-1 -f

bspc config border_width 2
bspc config borderless_monocle false

bspc config window_gap 7
bspc config split_ratio 0.50
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_border_color "#BF616A"
bspc config normal_border_color "#353b45"

bspc rule -a firefox desktop=III follow=on focus=on
bspc rule -a Chromium desktop=III follow=on focus=on

bspc rule -a mpv desktop=VII state=fullscreen follow=on focus=on

bspc rule -a obs desktop=VIII follow=on focus=on

bspc rule -a 'Tor Browser' desktop=XI follow=on focus=on
bspc rule -a librewolf desktop=XI follow=on focus=on
bspc rule -a qBittorrent state=tiled desktop=IX follow=on focus=on

bspc rule -a Virt-manager desktop=X follow=on focus=on
bspc rule -a Spotify state=tiled desktop=X follow=on focus=on
bspc rule -a discord state=tiled desktop=X follow=on focus=on

bspc rule -a *:*:Picture-in-Picture state=floating sticky=on center=on border=off
bspc rule -a pavucontrol state=floating center=on
bspc rule -a Viewnor state=floating center=on
bspc rule -a ExifCleaner state=floating center=on

## autostart up applications

# polkit-agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# polybar launch
$HOME/.config/polybar/launch.sh &

# picom (compositor)
DISPLAY=":0" picom &

# notification daemon
dunst &

# feh set wallpaper
~/.fehbg &

# lockscreen
$HOME/.scripts/lock_and_power/lock.sh &

# polybar cursor issue fix
xsetroot -cursor_name left_ptr &

## 'rofi-greenclip'
greenclip daemon &

# keybinds daemon
sxhkd
